In [1]:
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from itertools import combinations
from sklearn.decomposition import PCA
import scipy

In [2]:
ph=1.5574E-4
times=[1,2,3,6,7,9,13,16,21,24,31] 
pxt=[(x) for x in list(range(3,50,1))]
neh=range(1,120)
path="C:/Workplace/C++/d2ome_v2/v2/v2/bin/Debug/"

In [3]:
all_AAs=['a', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'p','q', 'r', 's', 't', 'v', 'w', 'y']
def charcount(pepSeq):
    res={key: 0 for key in all_AAs}     
    for c in pepSeq.lower():
        if c.isalpha():
            res[c]+=1
    return res

In [4]:
def getPeptiedsInfo(protien,time):

    peptides=[x.split('_1_')[0] for x in os.listdir(path) if ((protien+".csv" in x) and ("_1_" in x)) ]
    peptides=[x  for x in peptides if 'A' in x]
#     all_AAs=np.unique([c for c in ("".join(sorted([x.replace('_','').replace('2','').replace('3','') for x in peptides])).lower())])
    peptidesinfo=dict()
    len(peptides)

    for k in range(len(peptides)):
        data=pd.read_csv(f"C:/Workplace/C++/d2ome_v2/v2/v2/bin/Debug/{peptides[k]}_{time}_{protien}.csv")
        data["pxt_neh"]=data.NEH*data.pxt
        data=data[["NEH","pxt","RMSE","pxt_neh","T_NEH","NH"]] 
        minval=min(data.RMSE)

        data=data[data.RMSE==minval]

        peptidesinfo[peptides[k]]={"pxt_neh":float(data.pxt_neh),"T_NEH":float(data.T_NEH),"Seq":peptides[k],
                               "charcount":charcount(peptides[k])}
        
    print(len(peptides))    
    visited=set()
    visited.add(peptides[0].split('_')[1])
    coefficients=[]
    for k in range(0,len(peptides)-1):
        if(peptides[k+1].split('_')[1] in visited):
            continue

        pep1=peptidesinfo[peptides[k]]
        pep2=peptidesinfo[peptides[k+1]]    
        visited.add(peptides[k].split('_')[1])

        r=pep1["pxt_neh"]/pep2["pxt_neh"]
        coefficients.append([pep1["charcount"][c]-r*pep2["charcount"][c] for c in all_AAs])
        
    return peptides,peptidesinfo,all_AAs,np.array(coefficients)

In [5]:
def compute_result(peptides,peptidesinfo,all_AAs,sol):
    t_neh,e_neh=[],[]
    for i in range (len(peptides)):
        pep1=peptidesinfo[peptides[i]]
        p_neh=0
        for index,c in enumerate(all_AAs): 
            p_neh+=(pep1["charcount"][c]*sol[index]) 
        t_neh.append(pep1["T_NEH"])
        e_neh.append(p_neh)

    res=pd.DataFrame([peptides,t_neh,e_neh])
    res=res.transpose()
    res.columns=["peptides","True_NEH","e_NEH"]
    res["dif"]=abs(res.True_NEH-res.e_NEH)
#     print(np.mean(res.dif),np.median(res.dif),np.std(res.dif))
    return res.sort_values(by='dif')

In [6]:
time=31
a_val=4
proteins=["CPSM_MOUSE","FAS_MOUSE","DHB4_MOUSE","ASSY_MOUSE","ATPA_MOUSE","ATPB_MOUSE","BHMT1_MOUSE",
         "CLH1_MOUSE","DHE3_MOUSE","DHSO_MOUSE","ECHA_MOUSE",
         "G3P_MOUSE","HMCS2_MOUSE","HYES_MOUSE","MYH9_MOUSE","PYC_MOUSE","PYGL_MOUSE","SAHH_MOUSE",
         "SARDH_MOUSE","SBP1_MOUSE","THIM_MOUSE","TKT_MOUSE"]
# proteins=["CPT2_MOUSE"],,"FAS_MOUSE",
coefficients=np.array([])
_peptides,_peptidesinfo=[],[]
for protine in proteins:
    
    peptides1,peptidesinfo1,all_AAs1,coefficients1=getPeptiedsInfo(protine,time) 
    print(protine,len(all_AAs1)==20)
    if(coefficients.shape[0]==0):
        coefficients=coefficients1
    else:
        coefficients=np.concatenate((coefficients1,coefficients), axis=0)
    _peptides.append(peptides1)
    _peptidesinfo.append(peptidesinfo1)
    
sol=list(scipy.optimize.nnls(coefficients[:,1:],-a_val*coefficients[:,0])[0])
# sol=list(scipy.optimize.lsq_linear(coefficients[:,1:],-a_val*coefficients[:,0])[0])

sol.insert(0,a_val) 
print("\nValues\n","\n".join([all_AAs1[index]+"= "+str(x) for index,x in enumerate(sol)]))
res=pd.DataFrame()
for i in range(len(proteins)):
    res=pd.concat([res,compute_result(_peptides[i],_peptidesinfo[i],all_AAs1,sol)])

print("\nstats",np.mean(res.dif),np.median(res.dif),np.std(res.dif))

24
CPSM_MOUSE True
13
FAS_MOUSE True
6
DHB4_MOUSE True
10
ASSY_MOUSE True
15
ATPA_MOUSE True
15
ATPB_MOUSE True
4
BHMT1_MOUSE True
5
CLH1_MOUSE True
6
DHE3_MOUSE True
10
DHSO_MOUSE True
9
ECHA_MOUSE True
2
G3P_MOUSE True
4
HMCS2_MOUSE True
4
HYES_MOUSE True
3
MYH9_MOUSE True
9
PYC_MOUSE True
8
PYGL_MOUSE True
7
SAHH_MOUSE True
8
SARDH_MOUSE True
2
SBP1_MOUSE True
6
THIM_MOUSE True
6
TKT_MOUSE True

Values
 a= 4
c= 2.08513032433976
d= 2.7431091096231652
e= 4.0379741384704895
f= 0.8918200796933635
g= 1.4307315288540874
h= 1.112961935076099
i= 0.8060522922887539
k= 0.06726947630126096
l= 0.9515415836125418
m= 0.6412736295099033
n= 1.4095886195904592
p= 1.9760003077306187
q= 3.968345050559395
r= 2.0295014649728165
s= 1.6109704830213067
t= 0.12321098050238505
v= 0.8417603841519066
w= 0.16584936053030308
y= 1.2398123591632402

stats 1.7814257885359224 1.4686052426257596 1.3784349466160923

In [7]:
print("proteins",len(proteins),"peptides",res.shape[0])

proteins 22 peptides 176

In [8]:
res=res.sort_values(by='dif')
res.head(20)

                  peptides True_NEH      e_NEH       dif
2       _DFTATFGPLDSLNTR_2     22.0  21.999367  0.000633
1           _DLEAHIDTANK_2     22.0  21.994817  0.005183
1          _DATSLNQAALYR_2     27.0  27.027621  0.027621
2         _ALMGLYNGQVLcK_2     20.0  19.969268  0.030732
8           _HALIIYDDLSK_2     17.0   17.03242   0.03242
11  _SLQDIIAILGMDELSEEDK_2     39.0  38.945592  0.054408
21      _TSAcFEPSLDYMVTK_2     23.0  22.944054  0.055946
3     _AQFGSDLDAATQQLLSR_3     40.0  39.943083  0.056917
2     _AQFGSDLDAATQQLLSR_2     40.0  39.943083  0.056917
20    _TAVDSGIALLTNFQVTK_3     25.0  24.884124  0.115876
19    _TAVDSGIALLTNFQVTK_2     25.0  24.884124  0.115876
1        _AIEEQVAVIYAGVR_3     33.0  32.881724  0.118276
0        _AIEEQVAVIYAGVR_2     33.0  32.881724  0.118276
2        _ELEDATETADAMNR_2     35.0  34.878468  0.121532
3         _SVDPTLALSVYLR_2     20.0  19.871721  0.128279
3          _TFYASEDKLENR_3     23.0  23.142772  0.142772
9      _VLVcGAGPVGMVTLLV_2     20.0  20.181237  0.181237
1   _DAMLENQTPELFQDVNKPK_3     37.0  36.805722  0.194278
5        _LKEDTQVADVTTSR_3     24.0  24.204974  0.204974
0       _LEDTLWAGLTDQHVK_3     24.0  24.212157  0.212157

In [9]:
res.tail(20)

                  peptides True_NEH      e_NEH       dif
1        _AHGGYSVFAGVGER_3     30.0  26.329487  3.670513
2     _DMGMVTILVHNTASALR_3     28.0  24.258489  3.741511
4      _VSQPIEGHAASFAQFK_3     39.0  35.215021  3.784979
2       _PTGGAGAVAMLIGPK_2     29.0  25.106035  3.893965
0        _ARPEFMLPVHFYGR_4     28.0  24.050699  3.949301
14  _VLDSGAPIKIPVGPETLGR_3     34.0   30.03094   3.96906
6   _WSScNIFSTQDHAAAAIAK_3     43.0  39.012301  3.987699
8     _HLGIVGEcNIQFALHPT_3     32.0  27.936405  4.063595
2   _GFIGPGIDVPAPDMSTGER_2     37.0  32.925761  4.074239
1    _DILQDVLDADLSNEAFPF_2     34.0  38.261393  4.261393
3      _ANPIIGNGGAPDTTAR_2     34.0   29.69451   4.30549
12    _WLSTSIPEAQWQSSLAR_2     38.0  33.588093  4.411907
0     _AGPWTPEAAVEHPEAVR_3     45.0  40.587699  4.412301
7     _HIGSSVEFDWcAVSSIR_3     33.0  28.236585  4.763415
1      _IHEGcEEPATHNALAK_4     40.0  35.189371  4.810629
3     _GNAGQTNYGFANSTMER_2     36.0   31.18708   4.81292
8   _QGIQVLVSTSNVSSLEGAR_2     39.0  34.076727  4.923273
4    _LFDHPEVPTPPESASVSR_3     40.0  34.348527  5.651473
2       _RPISADSAIMNPASK_2     35.0  29.287759  5.712241
7        _GIRPAINVGLSVSR_3     28.0  21.775163  6.224837

In [10]:
temp=pd.DataFrame(coefficients)
temp.columns=all_AAs1
temp

,a,c,d,e,f,g,h,i,k,l,m,n,p,q,r,s,t,v,w,y
0,1.236842,0.00000,-1.842105,2.078947,1.000000,1.000000,0.000000,-2.763158,0.000000,3.078947,0.000000,0.078947,-1.763158,-0.921053,0.078947,-0.921053,-0.921053,0.078947,1.0,0.000000
1,1.869048,0.00000,-0.261905,1.000000,0.000000,-1.130952,-1.130952,1.869048,-1.130952,-1.261905,0.000000,1.000000,0.738095,-3.523810,1.000000,-0.130952,1.000000,-0.130952,0.0,-1.130952
2,-2.249516,0.00000,-1.249516,0.000000,-1.624758,-0.624758,1.000000,-2.249516,-2.249516,2.000000,-1.624758,0.000000,2.000000,2.375242,0.000000,1.000000,0.000000,-2.249516,0.0,1.000000
3,1.397084,0.00000,2.000000,-1.205831,1.000000,1.000000,0.000000,0.191253,1.397084,0.000000,0.397084,-0.602916,0.000000,-1.411662,0.000000,-1.205831,0.000000,1.397084,0.0,-0.602916
4,-0.429167,0.00000,-1.429167,0.570833,-1.429167,-1.429167,0.000000,3.000000,-0.429167,0.000000,-0.429167,1.000000,-2.858333,4.000000,0.000000,-2.287500,-2.858333,-3.287500,0.0,-0.429167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,-0.400001,0.00000,0.300000,1.000000,-0.700000,0.300000,1.000000,0.300000,0.300000,-0.400001,0.000000,-0.700000,0.000000,-0.700000,0.000000,-0.700000,-0.100001,-0.400001,0.0,0.000000
145,-0.034783,0.00000,-0.017391,0.000000,-0.017391,-0.017391,0.000000,-0.017391,-0.017391,-0.034783,0.000000,-0.017391,0.000000,-0.017391,0.000000,-0.017391,-0.052174,-0.034783,0.0,0.000000
146,0.933210,-1.06679,-0.066790,-1.066790,-0.066790,1.000000,0.000000,1.000000,-0.066790,0.933210,-1.066790,1.000000,-1.066790,1.000000,0.000000,-1.133581,0.866419,0.933210,0.0,-1.066790
147,0.137600,1.00000,1.000000,0.137600,1.000000,-0.862400,0.000000,-0.862400,0.137600,-0.724800,0.137600,-2.587200,0.137600,-0.862400,0.000000,1.137600,0.275200,-1.587200,0.0,1.000000
148,0.018838,0.00000,-0.981162,-0.962323,0.000000,0.018838,0.000000,0.018838,1.000000,1.018838,0.018838,3.000000,1.000000,1.000000,-0.981162,-0.962323,0.037677,1.037677,0.0,0.000000

In [11]:
# for c in range( len(coefficients)):
#     print(np.dot(coefficients[c],sol))