In [1]:
import numpy as np
import pandas as pd
from scipy.optimize import nnls

In [2]:
path="C:/Workplace/C++/d2ome_v2/v2/v2/bin/Debug/proportion_pxt_neh/"
time=31
pw=0.046

In [3]:
data=pd.read_csv(path+"__CPSM_MOUSE.csv")
data=data[data.exp_Time==time]
data=data[data.exp_Time==time].reset_index(drop="True")
data.head()

,Peptied,charge,exp_Time,NEH,e_NEH,pxt,e_pxt,mo,m1,m2,m3,m4,m5,io,i1,i2,i3,i4,i5
0,SMEYcIIEVNAR,2,31,25,22,0.046,0.050,0.40995,0.31550,0.17244,0.07014,0.02338,0.00661,0.131710,0.261299,0.278459,0.183605,0.105282,0.039646
1,IEFEGQSVDFVDPNK,2,31,28,27,0.046,0.050,0.36570,0.34991,0.18540,0.07061,0.02144,0.00548,0.099898,0.215021,0.271999,0.214834,0.134417,0.063831
2,TAVDSGIALLTNFQVTK,2,31,25,26,0.046,0.045,0.35488,0.35097,0.19026,0.07374,0.02269,0.00586,0.112706,0.241696,0.267777,0.206311,0.116566,0.054945
3,EPLFGISTGNIITGLAAGAK,3,31,36,32,0.046,0.048,0.32091,0.34919,0.20558,0.08588,0.02834,0.00782,0.075000,0.185255,0.252018,0.237232,0.162041,0.088454
4,PSYVLSGSAMNVVFSEDEMK,2,31,36,32,0.046,0.048,0.26161,0.31262,0.22573,0.12075,0.05225,0.01916,0.055720,0.167710,0.233795,0.236165,0.186275,0.120335

In [4]:
res=[]
for pep_index in range(data.shape[0]):
    exp_0=list(data.loc[pep_index,["mo","m1","m2","m3","m4","m5"]])
    b=list(data.loc[pep_index,["io","i1","i2","i3","i4","i5"]])#exp_t
    
    if (data.loc[pep_index,"Peptied"]!="DGSIDLVINLPNNNTK"):
        continue
        
    A=[]
    for i in range(6):
        A.append(([0]*i)+exp_0[:6-i])
    A=np.array(A).transpose()
#     x=np.matmul( np.linalg.inv ( np.matmul(A.transpose(),A)) , np.matmul(A.transpose(),b)  )
    x=list(nnls(A,b)[0])
    
    neh= (x[3]/x[2])*3* ((1-pw)/pw) +2
    xm=sum([(index+1)*val / sum(x) for index,val in enumerate(x)])
    res.append([data.loc[pep_index,"Peptied"],data.loc[pep_index,"charge"],data.loc[pep_index,"NEH"],neh,xm, 
               data.loc[pep_index,"e_NEH"]*data.loc[pep_index,"e_pxt"]])
    
    ypred=[np.dot(A[i],x) for i in range(A.shape[0])]
    sigma=sum([ (b[i]-y)**2 for index,y in enumerate(ypred)])/(len(ypred)-1)
    cov=((sigma)*np.linalg.inv(np.matmul(A.transpose(),A)))
    var=[cov[x][x] for x in range(6)]
    
    print(data.loc[pep_index,"Peptied"],nnls(A,b)[1])
    
#     print(data.loc[pep_index,"Peptied"],"\n",x,"\n",b,"\n",var,"\n")

#     print(data.loc[pep_index,"Peptied"],x,end="\n\n")

DGSIDLVINLPNNNTK 0.0059047067004823605
DGSIDLVINLPNNNTK 0.0

In [5]:
nnls(A,b)[1]

0.0

In [6]:
res=pd.DataFrame(res)
res.columns=["Peptide","Charge","True NEH","e NEH","sum_xi","pxt_neh"]
res["dif"]=abs(res["True NEH"]- res["e NEH"])
# res["test"]=100*abs(res["sum_xi"]-res["pxt_neh"])/res["pxt_neh"]
res=res.sort_values(by="dif")
res.head(70)

            Peptide  Charge  True NEH      e NEH    sum_xi   pxt_neh       dif
1  DGSIDLVINLPNNNTK       3        23  22.855625  1.947530  0.930999  0.144375
0  DGSIDLVINLPNNNTK       2        23  25.102248  2.131078  1.022000  2.102248

In [7]:
ypred=[np.dot(A[i],x) for i in range(A.shape[0])]
sigma=sum([ (b-x)**2 for x in ypred])/(len(ypred)-6-1)
cov=((sigma**2)*np.linalg.inv(np.matmul(A.transpose(),A)))
var=[cov[x][x] for x in range(6)]

ci_ub=[x[i]+1.96*var[i] for i in range(6)]
ci_lb=[x[i]-1.96*var[i] for i in range(6)]
ci=[1.96*var[i] for i in range(6)]

pd.DataFrame([x,ci,ci_ub,ci_lb]).transpose()

# temp=pd.DataFrame()
# temp["AA"]=all_AAs1
# temp["E_value"]=sol
# temp["T_value"]=trueval
# temp["var"]=var
# temp["CI"]=ci
# temp.sort_values(by="var")

          0         1         2         3
0  0.366601  0.058960  0.425560  0.307641
1  0.425935  1.162963  1.588898 -0.737029
2  0.159797  0.243457  0.403254 -0.083660
3  0.053565  0.098988  0.152553 -0.045423
4  0.004718  0.476442  0.481161 -0.471724
5  0.008018  0.853220  0.861238 -0.845202

In [8]:
res.to_csv("testx3x2.csv",index=False)